### CALCULATE THE CENTER OF A 3D CIRCLE FROM 3 COORDINATE

In [1]:
import numpy as np

In [100]:
# Define the 3 point of a vector

vA = np.array([-21.35,35.84,-20.61])
vB = np.array([-20.24,33.09,-24.09])
vC = np.array([-17.07,31.19,-20.29])

In [3]:
# Find the normal vector to the plane  of the 3 points

n_ = np.cross(vA,vB)+np.cross(vB,vC)+np.cross(vC,vA)

# Calculate th unit vector of it

n = n_ / np.linalg.norm(n_)

n

array([-0.71632544, -0.64023423,  0.27744911])

In [4]:
# Calculate mutually ortogonal directions

u_ = np.cross((vC-vA),n)     #projection 

u = u_ / np.linalg.norm(u_)  #unit vector x*
 
v = np.cross(n,u)            #unit vector y*

In [5]:
# Construct the rotation matrix

R = np.array([u,v])

R

array([[-0.17150241, -0.22387979, -0.95940855],
       [ 0.67636144, -0.73483194,  0.05056908]])

In [6]:
# Calculate the distance of the plane ABC from the origin

d = np.dot(n,vA)
d

-13.370672675357042

In [7]:
# Convert coordinate from 3D to 2D

va = np.dot(R,vA)
vb = np.dot(R,vB)
vc = np.dot(R,vC)

va,vb,vc

(array([ 15.41113477, -41.818922  ]),
 array([ 19.17517828, -39.22335338]),
 array([ 15.41113477, -35.49094444]))

In [8]:
# solve the system of equations to find the center

array1 = np.array([[(vb[0])-(va[0]),(vb[1])-(va[1])],[(vc[0])-(va[0]),(vc[1])-(va[1])]])
array1

array([[3.76404351e+00, 2.59556862e+00],
       [1.77635684e-15, 6.32797756e+00]])

In [9]:
array2 = np.array([[((vb[0]**2+vb[1]**2)-(va[0]**2+va[1]**2))/2],[((vc[0]**2+vc[1]**2)-(va[0]**2+va[1]**2))/2]])
array2

array([[ -40.0832 ],
       [-244.60755]])

In [10]:
# solve the sistem of equations to find the 2D coordinate of the center

ccoo = np.dot(array2.transpose(),np.linalg.inv(array1.transpose())).transpose()
ccoo

array([[ 16.00627933],
       [-38.65493322]])

In [17]:
# calculate the 3D coordinate of the center   *******************************

cc3d = np.dot(n,d).transpose()+np.dot(R.transpose(),ccoo).transpose()
np.round(cc3d,3)

#  the final coordinate of the centre are:

array([[-19.312,  33.382, -21.021]])

In [18]:
# Calculate the radius

r = np.linalg.norm(vA-cc3d)
r

3.219475429620807

####  We find the same result but with a 3d rotation matrix R3d

In [77]:
R3d = np.array([u,v,n])   # is the rotation array with z coordinate
ccoo_ = np.append(ccoo,0)
ccoo_

array([ 16.00627933, -38.65493322,   0.        ])

In [80]:
cc3d_ = np.dot(n,d).transpose()+np.dot(R3d.transpose(),ccoo_).transpose()
np.round(cc3d_,3)
# the result is the same

array([-19.312,  33.382, -21.021])

### WE NOW CREATE A CYLINDER

#####  1 method we create a cylinder perpendicular to the face

In [98]:
# WE ADD and SUBTRACT TO THE CENTRE 0.1m to create a cylinder (first we do it in the ficticious plane)

ccoo1 = ccoo_.copy()  # use copy to avoid modification to the original array ccoo_
ccoo1[2] = 0.25
ccoo2 = ccoo_.copy()
ccoo2[2] = -0.25
ccoo1,ccoo2

(array([ 16.00627933, -38.65493322,   0.25      ]),
 array([ 16.00627933, -38.65493322,  -0.25      ]))

In [83]:
###  Create the 3d coordinate of the two center

In [99]:
cc3d1 = np.dot(n,d).transpose()+np.dot(R3d.transpose(),ccoo1).transpose()
cc3d2 = np.dot(n,d).transpose()+np.dot(R3d.transpose(),ccoo2).transpose()
np.round(cc3d1,2),np.round(cc3d2,2)

(array([-19.49,  33.22, -20.95]), array([-19.13,  33.54, -21.09]))

##### 2 method create a cylinder along a direction (use two point along the lateral face)

In [85]:
p1 = np.array([-17.68,31,-22.19])
p2 = np.array([-14.98,32.85,-22.07])
p_ = p1-p2
p_[2]=0
p_

array([-2.7 , -1.85,  0.  ])

In [86]:
p = p_/np.linalg.norm(p_)
p

array([-0.82493237, -0.56523144,  0.        ])

In [89]:
cc3d1 = cc3d_ + p*1
cc3d2 = cc3d_ + p*(-1)
np.round(cc3d1,2),np.round(cc3d2,2)

(array([-20.14,  32.82, -21.02]), array([-18.49,  33.95, -21.02]))

##### 3 method use the normal vector projected on the orizontal plane

In [93]:
## Oppure usa le coordinate normali al piano ma proiettale sul piano hz ovvero forza la z=0

n_hz = n_.copy()
n_hz[2]=0

In [94]:
n_hz_norm = n_hz/np.linalg.norm(n_hz)
n_hz_norm

array([-0.74559734, -0.66639674,  0.        ])

In [95]:
cc3d1 = cc3d_ + n_hz_norm*0.5  # use copy to avoid modification to the original array ccoo_
cc3d2 = cc3d_ + n_hz_norm*(-0.5)
np.round(cc3d1,2),np.round(cc3d2,2)

(array([-19.68,  33.05, -21.02]), array([-18.94,  33.71, -21.02]))

## CREATE A FUNCTION

In [102]:
def calc_center (vA,vB,vC):
    
    # Find the normal vector to the plane  of the 3 points
    n_ = np.cross(vA,vB)+np.cross(vB,vC)+np.cross(vC,vA)

    # Calculate the unit vector of it
    n = n_ / np.linalg.norm(n_)
    
    # Calculate mutually ortogonal directions
    u_ = np.cross((vC-vA),n)     #projection 
    u = u_ / np.linalg.norm(u_)  #unit vector x* 
    v = np.cross(n,u)            #unit vector y*
    
    # Construct the rotation matrix
    R = np.array([u,v])
    
    # Calculate the distance of the plane ABC from the origin
    d = np.dot(n,vA)
    
    # Convert coordinate from 3D to 2D
    va = np.dot(R,vA)
    vb = np.dot(R,vB)
    vc = np.dot(R,vC)
    
    # solve the system of equations to find the center
    array1 = np.array([[(vb[0])-(va[0]),(vb[1])-(va[1])],[(vc[0])-(va[0]),(vc[1])-(va[1])]])
    array2 = np.array([[((vb[0]**2+vb[1]**2)-(va[0]**2+va[1]**2))/2],[((vc[0]**2+vc[1]**2)-(va[0]**2+va[1]**2))/2]])
    ccoo = np.dot(array2.transpose(),np.linalg.inv(array1.transpose())).transpose()

    # calculate the 3D coordinate of the center   *******************************
    cc3d = np.dot(n,d).transpose()+np.dot(R.transpose(),ccoo).transpose()
    np.round(cc3d,3)

    # Calculate the radius
    r = np.linalg.norm(vA-cc3d)
    
    
    return np.round(cc3d,3),r

In [104]:
# Define the 3 point of a vector

vA = np.array([-22.70,40.01,-20.55])
vB = np.array([-23.32,42.79,-24.08])
vC = np.array([-22.84,46.32,-21.29])


calc_center(vA,vB,vC)

(array([[-22.779,  43.159, -20.97 ]]), 3.1778108310166124)